# Generated by Django 5.1.7 on 2025-03-28 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20, verbose_name='ID пользователя')),
                ('username', models.CharField(max_length=50, verbose_name='Username пользователя')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='DaylyWriting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writing', models.TextField(blank=True, null=True, verbose_name='Записи за день')),
                ('day', models.DateField(verbose_name='Дата')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='bot.user')),
            ],
            options={
                'verbose_name': 'Запись за день',
                'verbose_name_plural': 'Записи за день',
            },
        ),
    ]
